import type {SidebarsConfig} from '@docusaurus/plugin-content-docs';

const sidebars: SidebarsConfig = {
  tutorialSidebar: [
    'intro',
    {
      type: 'category',
      label: 'Module 1: ROS 2',
      items: [{type: 'autogenerated', dirName: 'module1-ros2'}],
    },
    {
      type: 'category',
      label: 'Module 2: Digital Twin',
      items: [{type: 'autogenerated', dirName: 'module2-gazebo'}],
    },
    {
      type: 'category',
      label: 'Module 3: AI-Robot Brain',
      items: [{type: 'autogenerated', dirName: 'module3-isaac'}],
    },
    {
      type: 'category',
      label: 'Module 4: VLA',
      items: [{type: 'autogenerated', dirName: 'module4-vla'}],
    },
  ],
};

export default sidebars;
